---
version: "3"
services:
  gas-steady-state:
    image: lanl-ansi/gas-steady-state
    container_name: gasmodels
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ./data/model6ss_test_0:/data/input
      - ./data/output:/data/output
    command: |
      -p /data/input/
      -o /data/output/
      -n model6ss_test_0
