string(CONCAT GRAVITY_INCLUDE_DIR "$ENV{HOME}/Documents/research/Gravity/include/")
string(CONCAT OPTION_PARSER_INCLUDE_DIR "${PROJECT_SOURCE_DIR}/third_party/cpp_option_parser/")


set(GRAVITY_INCLUDE_DIRS ${GRAVITY_INCLUDE_DIR} ${OPTION_PARSER_INCLUDE_DIR})
set(GRAVITY_LIB_NAME "libgravity.a")

string(CONCAT GRAVITY_LIB_DIR "$ENV{HOME}/Documents/research/Gravity/lib/")


set(GRAVITY_LIBRARY "${GRAVITY_LIB_DIR}/${GRAVITY_LIB_NAME}" CACHE FILEPATH "GRAVITY library")
set(GRAVITY_LIBRARIES "${GRAVITY_LIBRARY}")

mark_as_advanced(GRAVITY_LIBRARY GRAVITY_INCLUDE_DIRS)


